### ISSUE TITLE
error with findContour

### ISSUE THREAD

**Issue by Lord-fourth** [AdityaPai2398/CamScanner-In-Python#1]
I'm getting this error while running
File "Scanner.py", line 18, in <module>
    image,contours,hierarchy=cv2.findContours(edged,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE)  #retrieve the contours as a list, with simple apprximation model
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by aravindkota** [comment]
> I'm getting this error while running
> File "Scanner.py", line 18, in
> image,contours,hierarchy=cv2.findContours(edged,cv2.RETR_LIST,cv2.CHAIN_APPROX_SIMPLE) #retrieve the contours as a list, with simple apprximation model
> ValueError: not enough values to unpack (expected 3, got 2)

check the version of opencv.
In the latest versions of opnecv( >4.0) the command cv2.findContours returns only two values i.e., contours & hierarchy.

**Comment by Lord-fourth** [comment]
@aravindkota yes I've figured it out but it is not working with every document

**Comment by desireend** [comment]
@Lord-fourth  can you share the solution?

**Comment by AdityaPai2398** [comment]
The fix is merged to master. Closing this
